### ISSUE TITLE
Not supported with android-apt plugin

### ISSUE THREAD

**Issue by ultraon** [PaNaVTEC/Coordinator-java#1]
Hi, i tried to use Coordinator library with annotations and bumped to following issues:
When i use android-apt plugin for Dagger, AndroidAnnotations... i can't use provided method in gradle dependencies, but when i use apt method then Coordinator annotations isn't found because it's located in coordinator-compiler module. As a result Coordinator.inject(this) doesn't work -> injector class isn't found.
Solution:
Make external module for lib with annotations and dependencies staff and include it in both modules (Coordinator & Coordinator-Compiler);

Then, as far as i know, this lib will work with android-apt plugin.

**Comment by PaNaVTEC** [comment]
Accepted, I'm releasing this as 1.1.0 later.

**Comment by PaNaVTEC** [comment]
Done, is released as 1.1.0. I'm closing this issue, if have any more problems re-open.

**Comment by ultraon** [comment]
Thank you, but what about deploying to maven repo?

**Comment by PaNaVTEC** [comment]
Man, gradle uses maven, is in maven central:

http://search.maven.org/#search%7Cga%7C1%7Ccoordinator

Also, why do you need apt? Since gradle 0.8.0 you can use provide.

**Comment by ultraon** [comment]
Yes, i use repositories { jcenter() } (it uses Bintray's JCenter), also i tried to use mavenCenteral() and got following error from gradle:

```
Error:(80, 0) Could not find Coordinator-java:coordinator-common:unspecified.
Required by:
    conrad-android-shopping-app:presentation:unspecified > me.panavtec:coordinator:1.1.0
<a href="searchInBuildFiles">Search in build.gradle files</a>
```

I use https://bitbucket.org/hvisser/android-apt plugin for generating code with AndroidAnnotations, Dagger and others.

**Comment by PaNaVTEC** [comment]
Um, sorry man, my fault. I forgot to upload the common module to maven :( I will upload it asap I don't have the key with me at this moment

**Comment by PaNaVTEC** [comment]
@ultraon Use 1.1.1 version, is solved.

**Comment by ultraon** [comment]
Thank you. But i have next issue.
If i use AndroidAnnotations library (https://github.com/excilys/androidannotations) Coordinator injects doesn't work, unfortunately. AndroidAnnotations extends my Android entities (Fragment, Activity...) with generated classes and generated classes use suffix '_'. So if i have Fragment with name MyFragment.java, AndroidAnnotations will generate MyFragment_.java, and real instance of "MyFragment" will be "MyFragment_". As a result while Coordinator.inject(this) method works it tries to find MyFragment_$$CoordinatorInjector, but there is only MyFragment$$CoordinatorInjector, and than i get ClassNotFoundException.

Could you please add support for famous library AndroidAnnotations?


```
public static <T> Coordinator inject(T source) {
    try {
      Class<?> injector = null;
      String className = source.getClass().getName();
      try {
          injector = Class.forName(className + "$$CoordinatorInjector");
      } catch (ClassNotFoundException e) {
          injector = Class.forName(className.substring(0, str.length() - 1) + "$$CoordinatorInjector");
      }
      Method inject = injector.getMethod("coordinateInject", source.getClass());
      return (Coordinator) inject.invoke(null, source);
    } catch (NoSuchMethodException e) {
      e.printStackTrace();
    } catch (ClassNotFoundException e) {
      e.printStackTrace();
    } catch (InvocationTargetException e) {
      e.printStackTrace();
    } catch (IllegalAccessException e) {
      e.printStackTrace();
    }
    return null;
  }
```

**Comment by PaNaVTEC** [comment]
Open another issue please, I will fix asap :+1:

**Comment by ultraon** [comment]
@PaNaVTEC Hi, today i found issue with resolving coordinator-common v.1.1.5 on jCenter (Bintray http://jcenter.bintray.com/me/panavtec/coordinator-common/1.1.5/) repository, that used by Android Gradle plugin by default. So, in this path http://jcenter.bintray.com/me/panavtec/coordinator-common/1.1.5/ only coordinator-common-1.1.5-javadoc.jar is located. On Maven Central repository - everything is good.

**Comment by PaNaVTEC** [comment]
@ultraon I'm not uploading anything on jcenter, is strange that common 1.1.5 is uploaded
