### ISSUE TITLE
Add supporting for AndroidAnnotations library

### ISSUE THREAD

**Issue by ultraon** [PaNaVTEC/Coordinator-java#2]
If i use AndroidAnnotations library (https://github.com/excilys/androidannotations) Coordinator injects doesn't work, unfortunately. AndroidAnnotations extends my Android entities (Fragment, Activity...) with generated classes and generated classes use suffix "&#95;". So if i have Fragment with name MyFragment.java, AndroidAnnotations will generate MyFragment_.java, and real instance of "MyFragment" will be "MyFragment_". As a result while Coordinator.inject(this) method works it tries to find MyFragment_$$CoordinatorInjector, but there is only MyFragment$$CoordinatorInjector, and than i get ClassNotFoundException.

Could you please add supporting for famous library AndroidAnnotations?

```
public static <T> Coordinator inject(T source) {
    try {
      Class<?> injector = null;
      Method inject = null;
      String className = source.getClass().getName();      
      try {
          injector = Class.forName(className + "$$CoordinatorInjector");
          inject = injector.getMethod("coordinateInject", source.getClass());
      } catch (ClassNotFoundException e) {
          injector = Class.forName(className.substring(0, className.length() - 1) + "$$CoordinatorInjector");
          inject = injector.getMethod("coordinateInject", source.getClass().getSuperclass());
      }
      return (Coordinator) inject.invoke(null, source);
    } catch (NoSuchMethodException e) {
      e.printStackTrace();
    } catch (ClassNotFoundException e) {
      e.printStackTrace();
    } catch (InvocationTargetException e) {
      e.printStackTrace();
    } catch (IllegalAccessException e) {
      e.printStackTrace();
    }
    return null;
  }
```

**Comment by PaNaVTEC** [comment]
Added support for inheritance. I have uploaded the 1.1.5 version and now this is supported.

**Comment by ultraon** [comment]
@PaNaVTEC Thank you very much, good job :-)

**Comment by PaNaVTEC** [comment]
Thanks to you for using and reporting. :)
